language: c

compiler: gcc

sudo: require

service:
  - docker

## NOTIFICATIONS
notifications:
  email:
    recipients:
    - florent.poinsard@epitech.eu
    - cecile.cadoul@epitech.eu
    on_success: never
    on_failure: always
  slack: epitech-tls-22:LRxgP10hWRPNZ3rSkuUMOTx0

jobs:
    include :
        - stage: build
          name: "Build"
          if: branch IN (master, dev, tests)
          before_script:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app"

        - stage: tests
          name: "Functional Tests"
          if: branch IN (master, dev, tests)
          before_script:
            - docker pull epitechcontent/epitest-docker
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd add"

        - stage: deploy
          name: "Deployement"
          if: branch = master AND type != cron
          before_script:
            - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
            - git checkout master
          script:
            - git push --repo=git@git.epitech.eu:/florent.poinsard@epitech.eu/PSU_2018_malloc --force
